DemoCCM1.2/DemoCCM/DemoCCM/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoCCM.Models;

namespace DemoCCM.Controllers
{
    public class TrangChuController : Controller
    {
        //
        // GET: /TrangChu/
        ConceptMapDBContext db = new ConceptMapDBContext();
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "About";
            return View();
        }
        public ActionResult _TrinhDoPartial()
        {
            List<Level> level = db.Levels.ToList();

            ViewBag.Message = "Trình Độ";
            return PartialView(level);
        }

       

    }
}

DemoCCM1.2/DemoCCM/DemoCCM/Views/Shared/_Concept.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/js")
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</head>
<body>
    <div class="main_container">
      <header>
        <div class="top_bar">
            <div class="top_login">
                <div class="text">User</div>
                <input type="text" class="class_input" name="user" />
                <div class="text">Password</div>
                <input type="password" class="class_input" name="pwd" />
                <input type="submit" class="btnsubmit" value="Login" />
            </div>
        </div> 
        <div id="header">
            <div id="logo">
            </div>
        </div>
        <div class="main_container">
            <nav class="menu_tab">
                <ul class="menu">
                         <li class="divider"></li>          
                         <li class="img_nav">@Html.ActionLink("Home","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav"> @Html.ActionLink("Giới Thiệu","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Liên Hệ","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Diễn Đàn","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Học Online","Index","TrangChu")</li>
                         <li class="divider"></li>                         
                 </ul>
            </nav>
        </div>  
     </header>
      
        @RenderBody()
   <footer>

   </footer>
</div>
    
</body>
</html>

DemoCCM1.2/DemoCCM/DemoCCM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/js_style.js")
</head>
<body>
    <div class="main_container">
      <header>
        <div class="top_bar">
            <div class="top_login">
                <div class="text">User</div>
                <input type="text" class="class_input" name="user" />
                <div class="text">Password</div>
                <input type="password" class="class_input" name="pwd" />
                <input type="submit" class="btnsubmit" value="Login" />
            </div>
        </div> 
        <div id="header">
            <div id="logo">

            </div>
        </div>
        <div class="main_container">
            <nav class="menu_tab">
                <ul class="menu">
                         <li class="divider"></li>          
                         <li class="img_nav">@Html.ActionLink("Home","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav"> @Html.ActionLink("Giới Thiệu","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Liên Hệ","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Diễn Đàn","Index","TrangChu")</li>
                         <li class="divider"></li>
                         <li class="no_img_nav">@Html.ActionLink("Học Online","Index","TrangChu")</li>
                         <li class="divider"></li>                         
                 </ul>
            </nav>
        </div>  
     </header>
        @{Html.RenderAction("_TrinhDoPartial", "TrangChu");}
        @RenderBody()
   <footer>

   </footer>
</div>
    
</body>
</html>