DemoCCM1.2/DemoCCM/DemoCCM/Models/Level.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.TopicOfLevels = new HashSet<TopicOfLevel>();
        }
    
        public string LevelID { get; set; }
        public string LevelName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TopicOfLevel> TopicOfLevels { get; set; }
    }
}

DemoCCM1.2/DemoCCM/DemoCCM/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoCCM.Models;
namespace DemoCCM.Controllers
{
    public class LevelController : Controller
    {

        //
        // GET: /ChuDe/
        ConceptMapDBContext db = new ConceptMapDBContext();

        public ActionResult Topic_Level(String levelID1,String topicId)
        {
             //Lấy Level đưa wa bên  Topic/Index
            ViewBag.topicId1 = topicId;
            List<TopicOfLevel> topicOfLevel = db.TopicOfLevels.Where(p => p.Level.LevelID.Equals(levelID1)).ToList();

            TopicOfLevel tp = topicOfLevel.Find(p => p.LevelID.Equals(levelID1));
            if(tp!=null)
            ViewBag.name = tp.Level.LevelName;

            ViewBag.Title = "Level";
            return View(topicOfLevel);
        }

     
       

    }
}

DemoCCM1.2/DemoCCM/DemoCCM/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DemoCCM.Models;

namespace DemoCCM.Controllers
{
    public class TopicController : Controller
    {
        //
        // GET: /ChuDe/

        ConceptMapDBContext db = new ConceptMapDBContext();

        public ActionResult Index(String LevelID1, String topicId1)
        {
            ViewBag.cd = new SelectList(db.ConceptsForTopics, "Question", "Question");
            ViewBag.levelID2 = LevelID1;
            ViewBag.topicID2 = topicId1;
            return View();

        }


        //Làm tương tự như Khái Niệm 
        public PartialViewResult _LinkOfTopicPartial(List<ConceptsForTopic> concept)
        {
            //Làm tương tự như Khái Niệm 


            List<Link> links = new List<Link>();

            var ids = from a in concept
                      select a.ConceptID;

            foreach (var id in ids)
            {
                var link = from p in db.Links
                           where p.ConceptID1.Equals(id) 
                           select p;
                foreach (Link i in link)
                {
                    links.Add(i);
                }
            }

            return PartialView(links);
        }

        public PartialViewResult _Concept_Topic_LevelPartial(String LevelID, String TopicID)
        {
            List<ConceptsForTopic> conceptForTopics;
            conceptForTopics = db.ConceptsForTopics.Where(p=>p.TopicID.Equals(TopicID)).ToList();
            List<ConceptsForTopic> conceptForTopics2 = new List<ConceptsForTopic>();
            ConceptsForTopic concept = new ConceptsForTopic();

            foreach (var k in conceptForTopics)
            {
                string[] catchuoi = k.Levels.Split(new char[] { ',' });
                foreach (string s1 in catchuoi)
                {

                    if (s1.Trim() != "")
                    {
                        if (s1.ToString().Equals(LevelID))
                        {

                            concept = conceptForTopics.Find(p => p.ConceptID.Equals(k.ConceptID));
                            conceptForTopics2.Add(concept);
                            
                        }
                    }

                }

            }

            return PartialView(conceptForTopics2);
        }

       
    }
}

DemoCCM1.2/DemoCCM/DemoCCM/Views/Level/Topic_Level.cshtml
@model List<DemoCCM.Models.TopicOfLevel>
@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
    String a = "";
   
    
}
 <article class="center_content">
     
                <div class="space"></div>
                <div class="center_title_bar">@ViewBag.name</div>
                <div class="center_main_content">
                    <ul id="thumbs">
                    @foreach (var e in Model)
                    {
                        a = e.Level.LevelName;
                        string name;

                        if (e.Topic.TopicImage == null)
                        {
                            name = "no_image.png";
                        }
                        else {
                            name = e.Topic.TopicImage;
                            
                        }
                        <li>
                            <a href="@Url.Action("Index","Topic",new{LevelID1=e.LevelID,topicId1=e.TopicID})"> @*idTopic=e.TopicID,*@
                                 <img alt="@e.Topic.ToppicName"  src="~/Photos/concepts/@name" />
                                 <div class="title_thumbs"></div>
                                 <span class="titlebla">@e.Topic.ToppicName </span>
                            </a>
                        </li>
                    }
                </ul>

                </div>
 </article>


